//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebStockMangement
{
    using System;
    using System.Collections.Generic;
    
    public partial class FARMER_PRODUCTS
    {
        public int PRODUCT_NUMBER { get; set; }
        public string FARMER_ID { get; set; }
        public string PRODUCT_NAME { get; set; }
        public string PRODUCT_TYPE { get; set; }
        public Nullable<System.DateTime> PROD_DATE { get; set; }
        public Nullable<int> QUANTIY { get; set; }
    
        public virtual FARMER FARMER { get; set; }
        public virtual PRODUCT PRODUCT { get; set; }
    }
}
