//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebStockMangement
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER
    {
        public int USER_ID { get; set; }
        public string FIRST_NAME { get; set; }
        public string SURNAME { get; set; }
        public string EMPLOYEE_ID { get; set; }
        public string FARMER_ID { get; set; }
        public string USER_ROLES { get; set; }
        public byte[] PasswordHash { get; set; }
        public string EMAIL { get; set; }
    
        public virtual EMPLOYEE EMPLOYEE { get; set; }
        public virtual FARMER FARMER { get; set; }
    }
}
